# Generated by Django 3.0.4 on 2020-03-27 09:01

#添加了latest news 数据表
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000, verbose_name='News Title')),
                ('Slug', models.SlugField(default='2020-03-27_17:01:27', unique=True, verbose_name='Slug')),
                ('Content', models.TextField(default='Please enter your news content here.', max_length=5000, verbose_name='News Content')),
                ('Date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('Date_edited', models.DateTimeField(auto_now=True, verbose_name='Last Edited Date')),
            ],
            options={
                'verbose_name': 'Latest News',
                'verbose_name_plural': 'Latest News',
                'ordering': ['Date_created'],
            },
        ),
    ]
