# Generated by Django 3.0.4 on 2020-03-27 17:08
#将latest news 数据表中的slug格式进行了修改

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-03-27_17_08_39', unique=True, verbose_name='Slug'),
        ),
    ]
