# Generated by Django 3.0.4 on 2020-03-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0002_auto_20200327_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=1000, verbose_name='File Name')),
                ('F_description', models.TextField(max_length=3000, verbose_name='File Description')),
                ('F_upload', models.FileField(upload_to='download_files', verbose_name='Upload File')),
                ('Date_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='First Uploaded Date')),
                ('Date_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
            ],
            options={
                'verbose_name': 'Downloads',
                'verbose_name_plural': 'Downloads',
            },
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-03-30_14_34_35', unique=True, verbose_name='Slug'),
        ),
    ]
