# Generated by Django 3.0.4 on 2020-03-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0003_auto_20200330_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='GGI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gene_name', models.CharField(max_length=100, verbose_name='Gene Name')),
                ('Target_name', models.CharField(max_length=1000, verbose_name='Targets')),
            ],
            options={
                'verbose_name': 'Gene-Gene Interaction',
                'verbose_name_plural': 'Gene-Gene Interaction',
            },
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-03-31_16_56_32', unique=True, verbose_name='Slug'),
        ),
    ]
