# Generated by Django 3.0.4 on 2020-04-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0004_auto_20200331_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='ggi',
            name='Diseases',
            field=models.CharField(default='Unknown', max_length=1000, verbose_name='Associated diseases'),
        ),
        migrations.AddField(
            model_name='ggi',
            name='Family_name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Family'),
        ),
        migrations.AddField(
            model_name='ggi',
            name='Symptoms',
            field=models.CharField(default='Unknown', max_length=1000, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='ggi',
            name='Virus',
            field=models.CharField(default='Unknown', max_length=1000, verbose_name='Virus'),
        ),
        migrations.AlterField(
            model_name='ggi',
            name='Gene_name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Gene Name'),
        ),
        migrations.AlterField(
            model_name='ggi',
            name='Target_name',
            field=models.CharField(default='Unknown', max_length=1000, verbose_name='Targets'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-09_15_32_11', unique=True, verbose_name='Slug'),
        ),
    ]
