# Generated by Django 3.0.4 on 2020-04-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0005_auto_20200409_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-09_15_35_38', unique=True, verbose_name='Slug'),
        ),
    ]
