# Generated by Django 3.0.4 on 2020-04-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0006_auto_20200409_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='ggi',
            name='PMID',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='PMID'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-09_15_37_14', unique=True, verbose_name='Slug'),
        ),
    ]
