# Generated by Django 3.0.4 on 2020-04-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0007_auto_20200409_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cytokine_names', models.CharField(max_length=1000, verbose_name='Cytokines')),
                ('Name', models.CharField(max_length=1000, verbose_name='Name')),
                ('Organization', models.CharField(max_length=1000, verbose_name='Organization')),
                ('E_mail', models.CharField(max_length=1000, verbose_name='E-mail')),
                ('PMID', models.CharField(max_length=1000, verbose_name='PMID')),
                ('Description', models.TextField(max_length=5000, verbose_name='Description')),
                ('Date_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='First Uploaded Date')),
                ('Date_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified Date')),
            ],
            options={
                'verbose_name': 'Data Submission',
                'verbose_name_plural': 'Data Submission',
            },
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-13_17_12_32', unique=True, verbose_name='Slug'),
        ),
    ]
