# Generated by Django 3.0.4 on 2020-04-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0008_auto_20200413_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_submission',
            name='Organization',
            field=models.CharField(default='Unknown', max_length=1000, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-13_19_43_57', unique=True, verbose_name='Slug'),
        ),
    ]
