# Generated by Django 3.0.4 on 2020-04-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0009_auto_20200413_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Virus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Virus_name', models.CharField(default='Unknown', max_length=100, verbose_name='Virus Name')),
                ('Other_names', models.CharField(max_length=300, verbose_name='Other Names')),
                ('Taxonomy', models.CharField(max_length=500, verbose_name='Taxonomy')),
                ('Viron', models.CharField(max_length=500, verbose_name='Viron')),
                ('Transmission', models.TextField(max_length=2000, verbose_name='Transmission')),
                ('Epidemiology', models.TextField(max_length=2000, verbose_name='Epidemiology')),
                ('Clinical_info', models.TextField(max_length=3000, verbose_name='Clinical Information')),
            ],
            options={
                'verbose_name': 'Virus Information',
                'verbose_name_plural': 'Virus Information',
            },
        ),
        migrations.AlterModelOptions(
            name='ggi',
            options={'ordering': ['Gene_name'], 'verbose_name': 'Gene-Gene Interaction', 'verbose_name_plural': 'Gene-Gene Interaction'},
        ),
        migrations.RemoveField(
            model_name='ggi',
            name='Virus',
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-16_15_39_33', unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='ggi',
            name='Virus',
            field=models.ManyToManyField(to='CSKD.Virus'),
        ),
    ]
