# Generated by Django 3.0.4 on 2020-04-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0010_auto_20200416_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-16_15_39_38', unique=True, verbose_name='Slug'),
        ),
    ]
