# Generated by Django 3.0.4 on 2020-04-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0011_auto_20200416_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='virus',
            name='More_info',
            field=models.CharField(default='#', max_length=1000, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-16_15_46_47', unique=True, verbose_name='Slug'),
        ),
    ]
