# Generated by Django 3.0.4 on 2020-04-16 17:12

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0012_auto_20200416_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Drug_name', models.CharField(max_length=200, verbose_name='Drug Name')),
                ('Drug_type', models.CharField(max_length=100, verbose_name='Type')),
                ('Drug_des', models.TextField(max_length=3000, verbose_name='Drug Description')),
                ('Structure', imagekit.models.fields.ProcessedImageField(upload_to='drug_imgs', verbose_name='Structure')),
                ('Synonyms', models.CharField(max_length=1000, verbose_name='Synonyms')),
                ('Other_info', models.CharField(max_length=500, verbose_name='More Information')),
            ],
            options={
                'verbose_name': 'Drug Information',
                'verbose_name_plural': 'Drug Information',
            },
        ),
        migrations.RemoveField(
            model_name='ggi',
            name='Diseases',
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-16_17_12_29', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='virus',
            name='Other_names',
            field=models.CharField(blank=True, max_length=300, verbose_name='Other Names'),
        ),
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease_name', models.CharField(max_length=100, verbose_name='Virus Name')),
                ('Other_names', models.CharField(blank=True, max_length=300, verbose_name='Other Names')),
                ('Description', models.TextField(max_length=3000, verbose_name='Other Information')),
                ('Drugs', models.ManyToManyField(to='CSKD.Drugs')),
            ],
            options={
                'verbose_name': 'Disease Information',
                'verbose_name_plural': 'Disease Information',
            },
        ),
        migrations.AddField(
            model_name='ggi',
            name='Diseases',
            field=models.ManyToManyField(to='CSKD.Diseases'),
        ),
    ]
