# Generated by Django 3.0.4 on 2020-04-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0013_auto_20200416_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ggi',
            name='Symptoms',
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-16_17_27_03', unique=True, verbose_name='Slug'),
        ),
    ]
