# Generated by Django 3.0.4 on 2020-04-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0014_auto_20200416_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='ggi',
            name='External_links',
            field=models.CharField(default='None', max_length=1000, verbose_name='External Links'),
        ),
        migrations.AddField(
            model_name='ggi',
            name='Function',
            field=models.TextField(default='Please describe its function here...', max_length=1000, verbose_name='Function'),
        ),
        migrations.AddField(
            model_name='ggi',
            name='Gene2Dis',
            field=models.TextField(default='Please describe how it is associated with diseases...', max_length=3000, verbose_name='Gene to Diseases'),
        ),
        migrations.AddField(
            model_name='ggi',
            name='Protein_name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Protein Name'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-16_17_32_37', unique=True, verbose_name='Slug'),
        ),
    ]
