# Generated by Django 3.0.4 on 2020-04-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0015_auto_20200416_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='virus',
            name='Related_dis',
            field=models.ManyToManyField(to='CSKD.Diseases'),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='Disease_name',
            field=models.CharField(max_length=100, verbose_name='Disease Name'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-16_20_03_19', unique=True, verbose_name='Slug'),
        ),
    ]
