# Generated by Django 3.0.4 on 2020-04-17 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0016_auto_20200416_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PMID', models.CharField(max_length=100, verbose_name='PMID')),
                ('Source', models.CharField(default='N/A', max_length=100, verbose_name='Source')),
                ('Institute', models.TextField(default='For mutiple institutes, use ";" to divide.', max_length=1000, verbose_name='Institutes')),
                ('Organism', models.CharField(choices=[('HS', 'Homo sapiens'), ('MM', 'Mus musculus'), ('RN', 'Rattus norvegicus'), ('CL', 'Cell_lines')], default='HS', max_length=2, verbose_name='Organism')),
                ('Cell_lines', models.CharField(blank=True, default='N/A', max_length=300, verbose_name='Cell lines')),
                ('Race', models.CharField(blank=True, default='N/A', max_length=200, verbose_name='Races')),
                ('Number', models.CharField(blank=True, default='N/A', max_length=1000)),
                ('Male', models.CharField(default='N/A', max_length=1000, verbose_name='Male sample size')),
                ('Female', models.CharField(default='N/A', max_length=1000, verbose_name='Female sample size')),
                ('age', models.CharField(default='* - *', max_length=100, verbose_name='Age range')),
                ('Experiment_methods', models.CharField(default='N/A', max_length=500, verbose_name='Experiments')),
                ('Other_info', models.TextField(default='N/A', max_length=1000, verbose_name='Other information')),
                ('Disease', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CSKD.Diseases', verbose_name='Disease')),
                ('Durgs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CSKD.Drugs', verbose_name='Drugs')),
                ('Virus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CSKD.Virus', verbose_name='Virus')),
            ],
        ),
        migrations.CreateModel(
            name='CytoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gene_name', models.CharField(default='Unknown', max_length=100, verbose_name='Gene Name')),
                ('Protein_name', models.CharField(default='Unknown', max_length=100, verbose_name='Protein Name')),
                ('Family_name', models.CharField(default='Unknown', max_length=100, verbose_name='Family')),
                ('Function', models.TextField(default='Please describe its function here...', max_length=1000, verbose_name='Function')),
                ('Target_name', models.CharField(default='Unknown', max_length=1000, verbose_name='Targets')),
                ('External_links', models.CharField(default='None', max_length=1000, verbose_name='External Links')),
                ('PMID', models.ManyToManyField(to='CSKD.Cases')),
            ],
            options={
                'verbose_name': 'Cytokine Information',
                'verbose_name_plural': 'Cytokine Information',
                'ordering': ['Gene_name'],
            },
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-17_11_28_16', unique=True, verbose_name='Slug'),
        ),
        migrations.DeleteModel(
            name='GGI',
        ),
    ]
