# Generated by Django 3.0.4 on 2020-04-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0019_auto_20200417_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cytoinfo',
            name='PMID',
            field=models.ManyToManyField(blank=True, to='CSKD.Cases'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-17_11_39_29', unique=True, verbose_name='Slug'),
        ),
    ]
