# Generated by Django 3.0.4 on 2020-04-17 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0020_auto_20200417_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='Disease',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CSKD.Diseases', verbose_name='Disease'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='Durgs',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CSKD.Drugs', verbose_name='Drugs'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='Virus',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CSKD.Virus', verbose_name='Virus'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-17_15_09_15', unique=True, verbose_name='Slug'),
        ),
    ]
