# Generated by Django 3.0.4 on 2020-04-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0021_auto_20200417_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='Female',
            field=models.CharField(blank=True, default='N/A', max_length=1000, verbose_name='Female sample size'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='Male',
            field=models.CharField(blank=True, default='N/A', max_length=1000, verbose_name='Male sample size'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='age',
            field=models.CharField(blank=True, default='* - *', max_length=100, verbose_name='Age range'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-17_15_11_04', unique=True, verbose_name='Slug'),
        ),
    ]
