# Generated by Django 3.0.4 on 2020-04-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0023_auto_20200417_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-17_15_19_42', unique=True, verbose_name='Slug'),
        ),
    ]
