# Generated by Django 3.0.4 on 2020-04-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0027_auto_20200417_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cases',
            options={'verbose_name': 'Cases', 'verbose_name_plural': 'Cases'},
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-17_15_25_24', unique=True, verbose_name='Slug'),
        ),
    ]
