# Generated by Django 3.0.4 on 2020-04-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0029_auto_20200417_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='cytoinfo',
            name='slug',
            field=models.SlugField(default=models.CharField(default='', max_length=100, verbose_name='Gene Name'), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='cytoinfo',
            name='Gene_name',
            field=models.CharField(default='', max_length=100, verbose_name='Gene Name'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-17_15_43_15', unique=True, verbose_name='Slug'),
        ),
    ]
