# Generated by Django 3.0.4 on 2020-04-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0030_auto_20200417_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cytoinfo',
            name='slug',
            field=models.SlugField(default='Must be unique', verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-17_15_44_29', unique=True, verbose_name='Slug'),
        ),
    ]
