# Generated by Django 3.0.4 on 2020-04-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0031_auto_20200417_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='Genes_involved',
        ),
        migrations.AddField(
            model_name='cases',
            name='Cytokines_involved',
            field=models.CharField(default='None', max_length=1000, verbose_name='Cytokines Involved'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-17_15_54_19', unique=True, verbose_name='Slug'),
        ),
    ]
