# Generated by Django 3.0.4 on 2020-04-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0032_auto_20200417_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cytoinfo',
            name='PMID',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Cytokines_involved',
        ),
        migrations.AddField(
            model_name='cases',
            name='Cytokines_involved',
            field=models.ManyToManyField(to='CSKD.CytoInfo'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-17_16_26_56', unique=True, verbose_name='Slug'),
        ),
    ]
