# Generated by Django 3.0.4 on 2020-04-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0033_auto_20200417_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cytoinfo',
            name='External_links',
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-17_18_57_19', unique=True, verbose_name='Slug'),
        ),
    ]
