# Generated by Django 3.0.4 on 2020-04-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0034_auto_20200417_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='Cell_lines',
            field=models.CharField(blank=True, default='N/A', max_length=100, verbose_name='Cell lines'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='Institute',
            field=models.TextField(default='For mutiple institutes, use ";" to divide.', max_length=200, verbose_name='Institutes'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='Number',
            field=models.IntegerField(blank=True, default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='cases',
            name='PMID',
            field=models.CharField(max_length=15, verbose_name='PMID'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='Race',
            field=models.CharField(blank=True, default='N/A', max_length=50, verbose_name='Races'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='Source',
            field=models.CharField(default='N/A', max_length=70, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-18_16_42_07', unique=True, verbose_name='Slug'),
        ),
    ]
