# Generated by Django 3.0.4 on 2020-04-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0037_auto_20200418_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='Number',
            field=models.IntegerField(blank=True, default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-18_16_43_46', unique=True, verbose_name='Slug'),
        ),
    ]
