# Generated by Django 3.0.4 on 2020-04-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0040_auto_20200418_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-18_16_45_43', unique=True, verbose_name='Slug'),
        ),
    ]
