# Generated by Django 3.0.4 on 2020-04-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0045_auto_20200418_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='Female',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cases',
            name='Male',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cases',
            name='Number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-18_16_48_56', unique=True, verbose_name='Slug'),
        ),
    ]
