# Generated by Django 3.0.4 on 2020-04-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0046_auto_20200418_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='Experiment_methods',
            field=models.CharField(default='N/A', max_length=150, verbose_name='Experiments'),
        ),
        migrations.AlterField(
            model_name='cytoinfo',
            name='Family_name',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='Family'),
        ),
        migrations.AlterField(
            model_name='cytoinfo',
            name='Gene_name',
            field=models.CharField(default='', max_length=10, verbose_name='Gene Name'),
        ),
        migrations.AlterField(
            model_name='cytoinfo',
            name='Target_name',
            field=models.CharField(default='Unknown', max_length=300, verbose_name='Targets'),
        ),
        migrations.AlterField(
            model_name='data_submission',
            name='Cytokine_names',
            field=models.CharField(max_length=100, verbose_name='Cytokines'),
        ),
        migrations.AlterField(
            model_name='data_submission',
            name='Description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='data_submission',
            name='E_mail',
            field=models.CharField(max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='data_submission',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='data_submission',
            name='Organization',
            field=models.CharField(default='Unknown', max_length=150, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='data_submission',
            name='PMID',
            field=models.CharField(max_length=100, verbose_name='PMID'),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='Description',
            field=models.TextField(max_length=1000, verbose_name='Other Information'),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='Other_names',
            field=models.CharField(blank=True, max_length=200, verbose_name='Other Names'),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='F_description',
            field=models.TextField(max_length=300, verbose_name='File Description'),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='F_name',
            field=models.CharField(max_length=100, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='Drug_des',
            field=models.TextField(max_length=1000, verbose_name='Drug Description'),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='Drug_name',
            field=models.CharField(max_length=100, verbose_name='Drug Name'),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='Other_info',
            field=models.CharField(max_length=1000, verbose_name='More Information'),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='Synonyms',
            field=models.CharField(max_length=500, verbose_name='Synonyms'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Content',
            field=models.TextField(default='Please enter your news content here.', max_length=500, verbose_name='News Content'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-18_16_52_52', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Title',
            field=models.CharField(max_length=100, verbose_name='News Title'),
        ),
        migrations.AlterField(
            model_name='virus',
            name='Clinical_info',
            field=models.TextField(max_length=1000, verbose_name='Clinical Information'),
        ),
        migrations.AlterField(
            model_name='virus',
            name='Epidemiology',
            field=models.TextField(max_length=500, verbose_name='Epidemiology'),
        ),
        migrations.AlterField(
            model_name='virus',
            name='Other_names',
            field=models.CharField(blank=True, max_length=150, verbose_name='Other Names'),
        ),
        migrations.AlterField(
            model_name='virus',
            name='Transmission',
            field=models.TextField(max_length=500, verbose_name='Transmission'),
        ),
        migrations.AlterField(
            model_name='virus',
            name='Virus_name',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='Virus Name'),
        ),
    ]
