# Generated by Django 3.0.4 on 2020-04-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0048_auto_20200418_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='Other_info',
        ),
        migrations.AddField(
            model_name='cases',
            name='Clinical_information',
            field=models.TextField(default='No clinical therapy information available.', max_length=300, verbose_name='Clinical Information'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Disease_stages',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Disease Stages'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Survival_stat',
            field=models.CharField(default='No statistics available.', max_length=100, verbose_name='Survival Statistics'),
        ),
        migrations.AddField(
            model_name='cytoinfo',
            name='Biomarkers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-18_17_09_12', unique=True, verbose_name='Slug'),
        ),
    ]
