# Generated by Django 3.0.4 on 2020-04-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0049_auto_20200418_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='Cytokines_involved',
            field=models.ManyToManyField(blank=True, to='CSKD.CytoInfo'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-18_17_12_44', unique=True, verbose_name='Slug'),
        ),
    ]
