# Generated by Django 3.0.4 on 2020-04-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0051_auto_20200418_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='Is_biomarker_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cases',
            name='biomarkers',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-18_17_22_58', unique=True, verbose_name='Slug'),
        ),
    ]
