# Generated by Django 3.0.4 on 2020-04-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0052_auto_20200418_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='Durgs',
            new_name='Drugs',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Clinical_information',
        ),
        migrations.AddField(
            model_name='cases',
            name='Biomarker_type',
            field=models.CharField(default='NA', max_length=2, verbose_name='Biomarker Type'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Disease_history',
            field=models.TextField(default='No disease history information available.', max_length=300, verbose_name='Disease History Information'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Drug_treatment_infomation',
            field=models.TextField(default='Include drug therapies history and duration', max_length=200, verbose_name='Drug Treatment Information'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Family_health_information',
            field=models.TextField(default='No family health history information available.', max_length=300, verbose_name='Family Health Information'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Treatment_information',
            field=models.TextField(default='No treatment information available.', max_length=300, verbose_name='Treatment Information'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-18_17_38_00', unique=True, verbose_name='Slug'),
        ),
    ]
