# Generated by Django 3.0.4 on 2020-04-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0053_auto_20200418_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='Biomarker_type',
            field=models.CharField(choices=[('PR', 'Prediction'), ('DI', 'Diagnosis'), ('PG', 'Prognosis'), ('NA', 'N/A'), ('OT', 'Other')], default='NA', max_length=2, verbose_name='Biomarker Type'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-18_17_41_30', unique=True, verbose_name='Slug'),
        ),
    ]
