# Generated by Django 3.0.4 on 2020-04-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0055_auto_20200422_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseases',
            name='symptoms',
            field=models.CharField(blank=True, max_length=200, verbose_name='Symptoms'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-22_16_19_53', unique=True, verbose_name='Slug'),
        ),
    ]
