# Generated by Django 3.0.4 on 2020-04-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0056_auto_20200422_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseases',
            name='Drugs',
        ),
        migrations.AddField(
            model_name='diseases',
            name='External_links_DOID',
            field=models.CharField(blank=True, max_length=10, verbose_name='Disease Ontology ID'),
        ),
        migrations.AddField(
            model_name='diseases',
            name='External_links_OMIM',
            field=models.CharField(blank=True, max_length=15, verbose_name='OMIM ID'),
        ),
        migrations.AddField(
            model_name='diseases',
            name='External_links_SNOMED',
            field=models.CharField(blank=True, max_length=15, verbose_name='SNOMED ID'),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='Other_names',
            field=models.CharField(blank=True, max_length=200, verbose_name='Synonym'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-23_15_48_14', unique=True, verbose_name='Slug'),
        ),
    ]
