# Generated by Django 3.0.4 on 2020-04-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0057_auto_20200423_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='Other_names',
            field=models.TextField(blank=True, max_length=500, verbose_name='Synonym'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-23_15_50_47', unique=True, verbose_name='Slug'),
        ),
    ]
