# Generated by Django 3.0.4 on 2020-04-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0058_auto_20200423_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseases',
            name='External_links_SNOMED',
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-23_16_01_58', unique=True, verbose_name='Slug'),
        ),
    ]
