# Generated by Django 3.0.4 on 2020-04-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0059_auto_20200423_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='Disease',
        ),
        migrations.AddField(
            model_name='cases',
            name='Disease',
            field=models.ManyToManyField(blank=True, to='CSKD.Diseases', verbose_name='Disease'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-23_16_23_35', unique=True, verbose_name='Slug'),
        ),
    ]
