# Generated by Django 3.0.4 on 2020-04-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0060_auto_20200423_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='Institute',
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-23_16_30_58', unique=True, verbose_name='Slug'),
        ),
    ]
