# Generated by Django 3.0.4 on 2020-04-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0061_auto_20200423_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-23_16_35_36', unique=True, verbose_name='Slug'),
        ),
    ]
