# Generated by Django 3.0.4 on 2020-04-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0062_auto_20200423_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='Drugs',
        ),
        migrations.AddField(
            model_name='cases',
            name='Drugs',
            field=models.ManyToManyField(blank=True, to='CSKD.Drugs', verbose_name='Drugs'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-23_17_11_12', unique=True, verbose_name='Slug'),
        ),
    ]
