# Generated by Django 3.0.4 on 2020-04-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0063_auto_20200423_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-23_20_02_53', unique=True, verbose_name='Slug'),
        ),
    ]
