# Generated by Django 3.0.4 on 2020-04-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0064_auto_20200423_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='Year',
            field=models.CharField(default=1900, max_length=4, verbose_name='Year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-23_20_11_31', unique=True, verbose_name='Slug'),
        ),
    ]
