# Generated by Django 3.0.4 on 2020-04-23 20:42

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0065_auto_20200423_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='Figure',
            field=imagekit.models.fields.ProcessedImageField(default='mechanism_figures/404.jpg', upload_to='mechanism_figures', verbose_name='Mechanism Figure'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-23_20_42_39', unique=True, verbose_name='Slug'),
        ),
    ]
