# Generated by Django 3.0.4 on 2020-04-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0066_auto_20200423_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='Organism',
            field=models.CharField(choices=[('HS', 'Homo sapiens'), ('MM', 'Mus musculus'), ('RN', 'Rattus norvegicus'), ('CL', 'Cell line')], default='HS', max_length=2, verbose_name='Organism'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-29_14_18_56', unique=True, verbose_name='Slug'),
        ),
    ]
