# Generated by Django 3.0.4 on 2020-04-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0067_auto_20200429_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='Organism',
            field=models.CharField(choices=[('HS', 'Homo sapiens'), ('MM', 'Mus musculus'), ('RN', 'Rattus norvegicus'), ('CL', 'Cell Line')], default='HS', max_length=2, verbose_name='Organism'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-29_14_19_42', unique=True, verbose_name='Slug'),
        ),
    ]
