# Generated by Django 3.0.4 on 2020-04-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0068_auto_20200429_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='Conclusion',
            field=models.TextField(default='N/A', max_length=1000, verbose_name='Conclusion'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-29_15_17_14', unique=True, verbose_name='Slug'),
        ),
    ]
