# Generated by Django 3.0.4 on 2020-04-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0069_auto_20200429_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-04-29_15_17_16', unique=True, verbose_name='Slug'),
        ),
    ]
