# Generated by Django 3.0.4 on 2020-07-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0070_auto_20200429_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='Biomarker_type',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Cell_lines',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Conclusion',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Cytokines_involved',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Disease',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Disease_history',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Disease_stages',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Drug_treatment_infomation',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Drugs',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Experiment_methods',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Family_health_information',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Female',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Figure',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Is_biomarker_reported',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Male',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Number',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Organism',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Race',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Source',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Survival_stat',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Treatment_information',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='Virus',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='age',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='biomarkers',
        ),
        migrations.RemoveField(
            model_name='virus',
            name='Related_dis',
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-07-06_10_11_43', unique=True, verbose_name='Slug'),
        ),
    ]
