# Generated by Django 3.0.4 on 2020-07-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0071_auto_20200706_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='Activated_partial_thromboplastin_time',
            field=models.CharField(choices=[('Inc', 'Increased'), ('Dec', 'Decreased'), ('Norm', 'Normal'), ('NM', 'Not Mentioned')], default='NM', max_length=4, verbose_name='Activated Partial Thromboplastin Time'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Adverse_event',
            field=models.TextField(blank=True, max_length=100, verbose_name='Adverse_event'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Age',
            field=models.CharField(blank=True, default='* - *', max_length=15, verbose_name='Age range'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Alanine_transferase',
            field=models.CharField(choices=[('Inc', 'Increased'), ('Dec', 'Decreased'), ('Norm', 'Normal'), ('NM', 'Not Mentioned')], default='NM', max_length=4, verbose_name='Alanine Transferase (ALT)'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Article_type',
            field=models.CharField(default='NA', max_length=30, verbose_name='Article Type'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Aspartate_transferase',
            field=models.CharField(choices=[('Inc', 'Increased'), ('Dec', 'Decreased'), ('Norm', 'Normal'), ('NM', 'Not Mentioned')], default='NM', max_length=4, verbose_name='Aspartate Transferase (AST)'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Biomarker_type',
            field=models.CharField(choices=[('PR', 'Prediction'), ('TR', 'Treatment'), ('DI', 'Diagnosis'), ('PG', 'Prognosis'), ('NA', 'NA'), ('OT', 'Other')], default='NA', max_length=2, verbose_name='Biomarker Type'),
        ),
        migrations.AddField(
            model_name='cases',
            name='CRS_name',
            field=models.CharField(default='NA', max_length=50, verbose_name='CRS Name'),
        ),
        migrations.AddField(
            model_name='cases',
            name='C_reactive_protein',
            field=models.CharField(choices=[('Inc', 'Increased'), ('Dec', 'Decreased'), ('Norm', 'Normal'), ('NM', 'Not Mentioned')], default='NM', max_length=4, verbose_name='C-Reactive Protein'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Cell_lines',
            field=models.CharField(blank=True, default='NA', max_length=50, verbose_name='Cell lines'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Creatinine',
            field=models.CharField(choices=[('Inc', 'Increased'), ('Dec', 'Decreased'), ('Norm', 'Normal'), ('NM', 'Not Mentioned')], default='NM', max_length=4, verbose_name='Creatinine (CR/Cre)'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Cytokine_down',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cytokine Down'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Cytokine_up',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cytokine Up'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Cytokines_involved',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cytokine Involved'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Cytokines_involved_down',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cytokine Involved Down'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Cytokines_involved_other',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cytokine Involved Other'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Cytokines_involved_up',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cytokine Involved Up'),
        ),
        migrations.AddField(
            model_name='cases',
            name='D_dimer',
            field=models.CharField(choices=[('Inc', 'Increased'), ('Dec', 'Decreased'), ('Norm', 'Normal'), ('NM', 'Not Mentioned')], default='NM', max_length=4, verbose_name='D-Dimer'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Discharge_time',
            field=models.CharField(blank=True, max_length=10, verbose_name='Discharge Time'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Disease',
            field=models.ManyToManyField(blank=True, to='CSKD.Diseases'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Disease_history',
            field=models.TextField(default='NA', max_length=300, verbose_name='Disease History'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Disease_induced',
            field=models.CharField(blank=True, max_length=100, verbose_name='Disease Induced'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Disease_stages',
            field=models.CharField(default='NA', max_length=30, verbose_name='Disease Stages'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Drug_associated',
            field=models.CharField(blank=True, max_length=50, verbose_name='Drugs Associated'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Drug_associated_dose',
            field=models.CharField(blank=True, max_length=30, verbose_name='Drug Associated Dose'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Drug_for_treatment',
            field=models.ManyToManyField(blank=True, to='CSKD.Drugs'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Drug_treatment_history',
            field=models.TextField(default='NA', max_length=300, verbose_name='Drug Treatment History'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Erythrocyte_sedimentation_rate',
            field=models.CharField(choices=[('Inc', 'Increased'), ('Dec', 'Decreased'), ('Norm', 'Normal'), ('NM', 'Not Mentioned')], default='NM', max_length=4, verbose_name='Erythrocyte Sedimentation Rate'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Experiment_methods',
            field=models.CharField(default='NA', max_length=150, verbose_name='Experiments'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Family_history',
            field=models.TextField(default='NA', max_length=300, verbose_name='Family Health History'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Female',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='cases',
            name='Fibrinogen',
            field=models.CharField(choices=[('Inc', 'Increased'), ('Dec', 'Decreased'), ('Norm', 'Normal'), ('NM', 'Not Mentioned')], default='NM', max_length=4, verbose_name='Fibrinogen'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Haemoglobin',
            field=models.CharField(choices=[('Inc', 'Increased'), ('Dec', 'Decreased'), ('Norm', 'Normal'), ('NM', 'Not Mentioned')], default='NM', max_length=4, verbose_name='Haemoglobin'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Immune_therapy_associated',
            field=models.CharField(blank=True, max_length=30, verbose_name='Immune Therapy Associated'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Is_biomarker_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cases',
            name='Lactate_dehydrogenase',
            field=models.CharField(choices=[('Inc', 'Increased'), ('Dec', 'Decreased'), ('Norm', 'Normal'), ('NM', 'Not Mentioned')], default='NM', max_length=4, verbose_name='Lactate Dehydrogenase (LDH)'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Leucocytes',
            field=models.CharField(choices=[('Inc', 'Increased'), ('Dec', 'Decreased'), ('Norm', 'Normal'), ('NM', 'Not Mentioned')], default='NM', max_length=4, verbose_name='Leucocytes'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Lymphocytes',
            field=models.CharField(choices=[('Inc', 'Increased'), ('Dec', 'Decreased'), ('Norm', 'Normal'), ('NM', 'Not Mentioned')], default='NM', max_length=4, verbose_name='Lymphocytes'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Male',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='cases',
            name='Neutrophils',
            field=models.CharField(choices=[('Inc', 'Increased'), ('Dec', 'Decreased'), ('Norm', 'Normal'), ('NM', 'Not Mentioned')], default='NM', max_length=4, verbose_name='Neutrophils'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='cases',
            name='Organism',
            field=models.CharField(choices=[('HS', 'Homo sapiens'), ('MM', 'Mus musculus'), ('RN', 'Rattus norvegicus'), ('CL', 'Cell Line'), ('OT', 'Other')], default='HS', max_length=2, verbose_name='Organism'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Other_treatment_targets',
            field=models.CharField(blank=True, max_length=50, verbose_name='Other Treatment Targets'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Other_treatments',
            field=models.CharField(blank=True, max_length=30, verbose_name='Other Treatment'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Pathogens',
            field=models.ManyToManyField(blank=True, to='CSKD.Virus'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Platelets',
            field=models.CharField(choices=[('Inc', 'Increased'), ('Dec', 'Decreased'), ('Norm', 'Normal'), ('NM', 'Not Mentioned')], default='NM', max_length=4, verbose_name='Platelets'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Procalcitonin',
            field=models.CharField(choices=[('Inc', 'Increased'), ('Dec', 'Decreased'), ('Norm', 'Normal'), ('NM', 'Not Mentioned')], default='NM', max_length=4, verbose_name='Procalcitonin'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Prothrombin_time',
            field=models.CharField(choices=[('Inc', 'Increased'), ('Dec', 'Decreased'), ('Norm', 'Normal'), ('NM', 'Not Mentioned')], default='NM', max_length=4, verbose_name='Prothrombin Time'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Race',
            field=models.CharField(blank=True, default='NA', max_length=50, verbose_name='Races'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Serum_ferritin',
            field=models.CharField(choices=[('Inc', 'Increased'), ('Dec', 'Decreased'), ('Norm', 'Normal'), ('NM', 'Not Mentioned')], default='NM', max_length=4, verbose_name='Serum Ferritin'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Soluble_CD25',
            field=models.CharField(choices=[('Inc', 'Increased'), ('Dec', 'Decreased'), ('Norm', 'Normal'), ('NM', 'Not Mentioned')], default='NM', max_length=4, verbose_name='Soluble CD25'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Source',
            field=models.CharField(default='NA', max_length=50, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Survival_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Survival Description'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Symptoms',
            field=models.CharField(blank=True, max_length=300, verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Temperature',
            field=models.CharField(blank=True, max_length=10, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Thrombin_time',
            field=models.CharField(choices=[('Inc', 'Increased'), ('Dec', 'Decreased'), ('Norm', 'Normal'), ('NM', 'Not Mentioned')], default='NM', max_length=4, verbose_name='Thrombin Time'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Treatment_dose',
            field=models.CharField(blank=True, max_length=30, verbose_name='Treatment Dose'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Treatment_target',
            field=models.CharField(blank=True, max_length=50, verbose_name='Treatment Targets'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Treatment_time',
            field=models.CharField(blank=True, max_length=10, verbose_name='Treatment Time'),
        ),
        migrations.AddField(
            model_name='cases',
            name='Triglyceride',
            field=models.CharField(choices=[('Inc', 'Increased'), ('Dec', 'Decreased'), ('Norm', 'Normal'), ('NM', 'Not Mentioned')], default='NM', max_length=4, verbose_name='Triglyceride'),
        ),
        migrations.AddField(
            model_name='cases',
            name='biomarkers',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='cases',
            name='slug',
            field=models.SlugField(default='Must be unique', verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='diseases',
            name='slug',
            field=models.SlugField(default='Must be unique', verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='drugs',
            name='slug',
            field=models.SlugField(default='Must be unique', verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='virus',
            name='slug',
            field=models.SlugField(default='Must be unique', verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='Drug_target',
            field=models.CharField(default='NA', max_length=150, verbose_name='Targets'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-07-06_16_03_29', unique=True, verbose_name='Slug'),
        ),
    ]
