# Generated by Django 3.0.4 on 2020-07-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0072_auto_20200706_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='Pathogens',
        ),
        migrations.AddField(
            model_name='cases',
            name='Pathogens',
            field=models.CharField(default='NA', max_length=50, verbose_name='Pathogens'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-07-30_19_46_32', unique=True, verbose_name='Slug'),
        ),
        migrations.DeleteModel(
            name='Virus',
        ),
    ]
