# Generated by Django 3.0.4 on 2020-09-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0075_auto_20200907_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='CRS_type',
            field=models.CharField(default='NA', max_length=100, verbose_name='CRS Type'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-09-24_14_42_30', unique=True, verbose_name='Slug'),
        ),
    ]
