# Generated by Django 3.0.4 on 2020-09-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSKD', '0076_auto_20200924_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='CRS_name',
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='Slug',
            field=models.SlugField(default='2020-09-24_20_18_49', unique=True, verbose_name='Slug'),
        ),
    ]
